#pragma once
namespace MX28
{
  enum MX28
  {
    //ADDR_TORQUE_ENABLE = 64,
    //ADDR_GOAL_VELOCITY = 104,
    //ADDR_GOAL_POSITION = 116,
    //ADDR_PROFILE_VEL = 112,

    //ADDR_PRESENT_CURRENT = 126,
    //ADDR_PRESENT_VELOCITY = 128,
    //ADDR_PRESENT_POSITION = 132,
    //ADDR_PRESENT_TEMPERATURE = 146,

    //ADDR_INDIRECT_ADDR_1 = 168,
    //ADDR_INDIRECT_DATA_1 = 224,

    //LENGTH_TORQUE_ENABLE = 1,
    //LENGTH_PRESENT_CURRENT = 2,
    //LENGTH_PRESENT_POSITION = 4,
    //LENGTH_PRESENT_TEMPERATURE = 1,

    //LENGTH_INDIRECT_ADDR_1 = 2,
    //LENGTH_INDIRECT_DATA_1 = 1

    ADDR_OPERATING_MODE = 11,
    ADDR_TORQUE_ENABLE = 64,
    ADDR_GOAL_PWM = 100,
    //ADDR_GOAL_CURRENT = 102,
    ADDR_GOAL_VELOCITY = 104,
    ADDR_GOAL_POSITION = 116,
    ADDR_PROFILE_VEL = 112,

    //ADDR_PRESENT_CURRENT = 126,
    ADDR_PRESENT_VELOCITY = 128,
    ADDR_PRESENT_POSITION = 132,
    ADDR_PRESENT_TEMPERATURE = 146,

    ADDR_INDIRECT_ADDR_1 = 168,
    ADDR_INDIRECT_DATA_1 = 224,

    LENGTH_TORQUE_ENABLE = 1,
    LENGTH_PRESENT_POSITION = 4,
    LENGTH_PRESENT_TEMPERATURE = 1,

    LENGTH_INDIRECT_ADDR_1 = 2,
    LENGTH_INDIRECT_DATA_1 = 1
  };
}